Models/Animal.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace AnimalPlaceProject.Models
{
	public class Animal
	{
		public int AnimalId { get; set; }
		[Required]
		public string? Name { get; set; }
		[Required]
		public double? Age { get; set; }

		public string? PictureName { get; set; }
		[MaxLength(100)]
		public string? Description { get; set; }
		[Required]
		public int? CategoryId { get; set; }

		public virtual Category? Category { get; set; }

		public virtual ICollection<Comment>? Comments { get; set; }

		
	}
}

Models/BlogPost.cs
using Microsoft.Build.Framework;

namespace AnimalPlaceProject.Models
{
    public class BlogPost
    {
        public int Id { get; set; }
        [Required]

        public string? Title { get; set; }
        [Required]
        public string? Content { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace AnimalPlaceProject.Models
{
	public class Category
	{
		public int CategoryId { get; set; }
		[Required]
		public string? Name { get; set; }

		public virtual ICollection<Animal>? Animals { get; set; }
	}
}

Models/Comment.cs
using System.ComponentModel.DataAnnotations;

namespace AnimalPlaceProject.Models
{
	public class Comment
	{
		public int Id { get; set; }
		[Required, MaxLength(50)]
		public string? Content { get; set; }
		public int? animalId { get; set; }
        public int? numOfLikes { get; set; }
		public bool? isLiked { get; set; }	
        public virtual Animal? Animal { get; set; }

	}
}

Models/LoginModel.cs
using Microsoft.Build.Framework;
using Microsoft.EntityFrameworkCore;

namespace AnimalPlaceProject.Models
{
    public class LoginModel
    {
        public int Id { get; set; }
        [Required]

        public string? Username { get; set; }
        [Required]
        public string? Password { get; set; }
    }
}

Controllers/AccountController.cs
using AnimalPlaceProject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnimalPlaceProject.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Username!, model.Password!, false, false);
               if(result.Succeeded)
                {
                    ViewBag.User = model;
                    return RedirectToAction("Index", "Home", model);
                }
            }
            return View();
        }
        public IActionResult Logout()
        {
            _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");   
        }
        public async Task<IActionResult> Register()
        {
            IdentityUser user = new IdentityUser()
            {
                UserName = "User123",
            };

            var result = await _userManager.CreateAsync(user, "123qwe!@#QWE");

            if(result.Succeeded)
            {
                return Content("Ok");
            }
            else
            {
                var errorMessage = string.Join(", ", result.Errors.Select(error => error.Description));
                return Content($"Failed: {errorMessage}");
            }
        }
    }
} 

Controllers/BlogController.cs
using AnimalPlaceProject.Models;
using Microsoft.AspNetCore.Mvc;
using AnimalPlaceProject.Services.BlogRepository;
using AnimalPlaceProject.Data;

namespace AnimalPlaceProject.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository _blogRepository;
        public BlogController(IBlogRepository blogRepository)
        {
            _blogRepository = blogRepository;
        }
        public IActionResult Index()
        {
            return View(_blogRepository.GetAllPosts());
        }

        public IActionResult Details(int id)
        {
            var blogPost = _blogRepository.GetPostById(id);
            return View(blogPost);
        }

    }
}

Controllers/CatalogController.cs
using AnimalPlaceProject.Data;
using AnimalPlaceProject.Models;
using AnimalPlaceProject.Services;
using AnimalPlaceProject.Services.AnimalRepository;
using AnimalPlaceProject.Services.CategoryRepository;
using AnimalPlaceProject.Services.CommentRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Scripting;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;

namespace AnimalPlaceProject.Controllers
{
    public class CatalogController : Controller
	{
		private IAnimalRepository _animalRepository;
		private ICategoriesRepository _categoriesRepository;
		private ICommentsRepository _commentsRepository;
		public CatalogController(IAnimalRepository animalRepository, ICategoriesRepository categoriesRepository, ICommentsRepository commentsRepository)
		{
		    _animalRepository = animalRepository;
			_categoriesRepository = categoriesRepository;
			_commentsRepository = commentsRepository;
		}

		public IActionResult Index(string categoryName = "All")
		{

			ViewBag.Categories = _categoriesRepository.GetAllCategories();

            ViewBag.CurrentCategory = categoryName;

            if (categoryName == "All")
			{
                return View(_animalRepository.GetAllAnimals());
            }
            return View(_animalRepository.GetAnimals(categoryName));
        }

		public IActionResult Details(int animalId)
		{
            return View(_animalRepository.GetAnimalById(animalId));
        }

		public IActionResult AddComment(string content, int animalId)
		{

			if(content == null)
			{
                return View("Details", _animalRepository.GetFirst(animalId));
            }

			_commentsRepository.AddComment(content, _animalRepository.GetFirst(animalId));
            return View("Details", _animalRepository.GetFirst(animalId));
		}

		public IActionResult AddLike(int commentId, int animalId, bool isLiked)
		{

			_commentsRepository.AddLike(commentId, isLiked);

            return View("Details", _animalRepository.GetFirst(animalId));
        }
    }

}


Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalPlaceProject.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult Index()
        {
            return Content("There was an unexpected error. Please come back later");
        }
    }
}

Controllers/HomeController.cs
using AnimalPlaceProject.Data;
using AnimalPlaceProject.Models;
using AnimalPlaceProject.Services.AnimalRepository;
using AnimalPlaceProject.Services.BlogRepository;
using Microsoft.AspNetCore.Mvc;

namespace AnimalPlaceProject.Controllers
{
    public class HomeController : Controller
	{
	    private IAnimalRepository _animalRepository;
		private IBlogRepository _blogRepository;

		public HomeController(MyContext context, IAnimalRepository animalRepository, IBlogRepository blogRepository)
		{
			_animalRepository = animalRepository;
		    _blogRepository = blogRepository;
		}
		public IActionResult Index(LoginModel model)
		{
			if(model != null)
			{
                ViewBag.User = model;
            }
            ViewBag.Post = _blogRepository.GetLastPost();
            return View(_animalRepository.GetAllAnimals());
		}
	}
}

Views/Admin/AddNew.cshtml

@{
    ViewData["Title"] = "AddNew";
}

<h1>Add New Animal</h1>

<a class="btn btn-primary" role="button" asp-controller="Admin" asp-action="Index" asp-route-animalId="" asp-route-categoryName="">Back</a>

<div>
     <form id="addForm" action="@Url.Action("Add", "Admin")" method="post" enctype="multipart/form-data">

         
       
        <input name="animalId" type="hidden" value="" />
        <br />


        <label for="animalName" class="col-form-label">Name:</label>
        <input name="animalName" type="text" value="" class="form-control" required/>

        <br />

        <label for="animalAge" class="col-form-label">Age:</label>
        <input name="animalAge" type="number" value="" class="form-conrol" required min="0" />
        <br /><br />

        <label for="animalImage" class="col-form-label">Image: </label>
        <img id="previewImage" src="" alt="Current Image" class="current-image" />
        <br> <br />
        <input id="imageInput" name="imageName" type="file" class="btn btn-secondary form-control-md" accept="image/*" required/>
        <br /> <br />

        <label for="description" class="col-form-label">Description:</label>
        <input name="description" id="description" type="text" value="" class="form-control" rows="5" maxlength="100" required />
        <p id="message"></p>

        <br /> <br />

        <label for="category" class="col-form-label">Category</label>
        <select id="categoryId" name="categoryId" required>
            @foreach (Category category in ViewBag.Categories)
            {
                <option value="@category.CategoryId">@category.Name</option>
            }
        </select>

        <br /> <br />

        <input id="commentBtn" class="MyBtn" type="submit" value="Save" />

        

</form>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script>
    $(document).ready(function () {
        $('#addForm').attr('id', 'addForm');
        $('#addForm').validate();
    });


    //-----------------------------



    let description = document.querySelector("#description");
    let maxLength = 100;
    let message = document.querySelector("#message");
    var checkLength = function () {
        if (description.value.length < maxLength) {
            message.innerHTML = (maxLength - description.value.length) + " characters remaining";
        }
        else {
            message.innerHTML = "No characters remaining";
        }
    }

    setInterval(checkLength, 50);




    // -----------------------------------------------


    const imageInput = document.querySelector("#imageInput");
    const previewImage = document.querySelector("#previewImage");

    imageInput.addEventListener("change", function () {
        const file = imageInput.files[0];
        const reader = new FileReader();

        reader.onload = function (e) {
            previewImage.src = e.target.result;
        };

        if (file) {
            reader.readAsDataURL(file);
        }
    });



</script>

Views/Admin/CreateBlogPost.cshtml
@model AnimalPlaceProject.Models.BlogPost

@{
    ViewData["Title"] = "CreateBlogPost";
}


<h1>Create Blog Post</h1>

<a class="btn btn-primary" role="button" asp-controller="Admin" asp-action="Index" asp-route-animalId="" asp-route-categoryName="">Back</a>


@using (Html.BeginForm("CreateBlogPost", "Admin", FormMethod.Post))
{
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" id="title" required/>
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea asp-for="Content" id="content" class="form-control" rows="7" maxlength="1000" required></textarea>
        <span asp-validation-for="Content" class="text-danger"></span>
    </div>

    <p id="message"></p>

    <button type="submit" class="btn btn-primary">Create</button>
}

<script>


    let title = document.querySelector("#title");
    function validateForm() {
        if (title.value == null || title.value.trim() === "") {
            showAlert();
            alert("Can't send an empty comment");
            return false;
        }

    }
    title.addEventListener("click", validateForm);

    //-----------------------

    let content = document.querySelector("#content");
    let maxLength = 1000;
    let message = document.querySelector("#message");
    var checkLength = function () {
        if (content.value.length < maxLength) {
            message.innerHTML = (maxLength - content.value.length) + " characters remaining";
        }
        else {
            message.innerHTML = "No characters remaining";
        }
    }

    setInterval(checkLength, 50);


</script>

Views/Admin/Edit.cshtml
@model AnimalPlaceProject.Models.Animal
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<a class="btn btn-primary" role="button" asp-controller="Admin" asp-action="Index" asp-route-animalId="" asp-route-categoryName="">Back</a>

<div>
    <form id="editForm" action="@Url.Action("EditPage", "Admin", new { animalId = Model.AnimalId })" method="post" enctype="multipart/form-data">


        <input name="animalId" type="hidden" value="@Model.AnimalId" />
        <br />

        <label for="animalName" class="col-form-label">Name:</label>
        <input name="animalName" id="nameInput" type="text" value="@Model.Name" class="form-control" required />
        <br />

        <label for="animalAge" class="col-form-label">Age:</label>
        <input name="animalAge" type="number" value="@Model.Age" class="form-conrol" required min="0"/>
        <br /><br />

        <label for="animalImage" class="col-form-label">Image: </label>
        <img id="previewImage" src="~/Pictures/@Model.PictureName" alt="Current Image" class="current-image" />
        <br /> <br />

        <input id="imageInput" name="imageName" type="file" value="@Model.PictureName" class="btn btn-secondary form-control-md" accept="image/*"/>

        <br /> <br />

        <label for="description" class="col-form-label">Description:</label>
        <input name="description" id="description" type="text" value="@Model.Description" class="form-control" maxlength="100" rows="5" required />
        <p id="message"></p>
        <br />

        <label for="categoryName" class="col-form-label">Category</label>
        <select id="categoryName" name="categoryName" required>
        <option value="@Model.CategoryId">@Model.Category.Name</option>
        @foreach (var category in ViewBag.Categories)
        {
            <option value="@category.Name">@category.Name</option>        
        }
        </select>
        <br />
        <input id="submitBtn" class="MyBtn" type="submit" value="Save" />
        </form>

</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script>
    $(document).ready(function () {
        $('#editForm').attr('id', 'editForm');
        $('#editForm').validate();
    });

    const nameInput = document.querySelector("#nameInput");
    const submitBtn = document.querySelector("#submitBtn");
    submitBtn.addEventListener("click", function(){
        if(nameInput.textContent.trim == "" || nameInput.textContent == null || nameInput < 0){
            event.preventDefault();
            event.stopPropagation();
            alert("Error");
        }
    })



    //------------------------------


    let description = document.querySelector("#description");
    let maxLength = 100;
    let message = document.querySelector("#message");
    var checkLength = function () {
        if (description.value.length < maxLength) {
            message.innerHTML = (maxLength - description.value.length) + " characters remaining";
        }
        else {
            message.innerHTML = "No characters remaining";
        }
    }

    setInterval(checkLength, 50);


    // -----------------------------------


    const imageInput = document.querySelector("#imageInput");
    const previewImage = document.querySelector("#previewImage");

    imageInput.addEventListener("change", function () {
        const file = imageInput.files[0];
        const reader = new FileReader();

        reader.onload = function (e) {
            previewImage.src = e.target.result;
        };

        if (file) {
            reader.readAsDataURL(file);
        }
    });

</script>

Views/Admin/Index.cshtml
@model IEnumerable<AnimalPlaceProject.Models.Animal>

@{
    ViewData["Title"] = "Index";
}

<h1>Admin</h1>
<p>Choose a Category:</p>
<div class="centeredDiv">
    <form action="/Admin/Index" method="post"  id="CategoryForm">
        <fieldset>
          
            <select name="categoryName" class="btn btn-secondary btn-md dropdown-toggle" onchange="SubmitForm()">

                @{
                    <option disabled selected>@ViewBag.CurrentCategory </option>
                    <option value="All">All</option>

                    if (ViewBag.Categories != null)
                    {
                        foreach (Category category in ViewBag.Categories)
                        {
                            <option value="@category.Name">@category.Name</option>
                        }
                    }
                    }
                    </select>

        </fieldset>
    </form>
</div>

<br />



<div>
    <table class="table">
        <tr>
            <th>Portrait</th>
            <th>Name</th>
            <th>find out more and comment</th>
            <a class="btn btn-dark" role="button" asp-controller="Admin" asp-action="AddNew">New Animal</a>
            <br />
            <br />
            <a class="btn btn-dark" role="button" asp-controller="Admin" asp-action="CreateBlogPost">New Blog Post</a>

        </tr>
        <br />
        <br />
        @{if(Model != null)
        foreach (var animal in Model)
        {

            <tr>
                        <td><img width="200" height="200" src="~/Pictures/@animal.PictureName" /></td>
                <td>@animal.Name</td>
                <td>
                   
                    <a class="btn btn-primary" id="btnDelete" role="button" asp-controller="Admin" asp-action="Delete" asp-route-animalId="@animal.AnimalId" asp-route-categoryName="@Model">Delete</a>
                    <a class="btn btn-primary" role="button" asp-controller="Admin" asp-action="Edit" asp-route-animalId="@animal.AnimalId" asp-route-categoryName="@Model">Edit</a>
                </td>

            </tr>

        }
        }
    </table>
</div>

<script>

﻿function SubmitForm() {
	document.getElementById("CategoryForm").submit();
}


</script>

Views/Blog/Details.cshtml
@model BlogPost
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<h1>@Model.Title</h1>
<p>@Model.CreateDate.ToString("yyyy-MM-dd")</p>
<p>@Model.Content</p>

Views/Blog/Index.cshtml
@model IEnumerable<AnimalPlaceProject.Models.BlogPost>
@{
    ViewData["Title"] = "Index";
}

<h1>Blog</h1>

<ul class="blogul">
    @foreach (var post in Model)
    {
        <li class="blog-post">
            <h3 class="blog-post">@post.Title</h3>
            <p>@post.CreateDate.ToString("yyyy-MM-dd")</p>
            <a href="@Url.Action("Details", new { id = post.Id })">Read More</a>
        </li>
    }
</ul>

Views/Catalog/Details.cshtml
@model AnimalPlaceProject.Models.Animal
@{
    ViewData["Title"] = "Details";
}


<h1>Details</h1>
<p class="h4">@Model.Name</p>

<img src="~/Pictures/@Model.PictureName" alt="Current Image" class="current-image" />
<table class ="table">
    <thead class="thead-dark">
    <tr>

        <th>Name:</th>
        <th>Description:</th>
        <th>Category:</th>
    </tr>
    <tr>
         
        <td>@Model.Name</td>
        <td>@Model.Description</td>
        <td>@Model.Category?.Name</td>        
    </tr>
    </thead>

    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Comments:</th>
        </tr>
       </thead>
        <tbody>
        @foreach (var comment in Model.Comments!)
        {

                <tr>
            <th scope="row">@comment.Content
                        <span>@comment.numOfLikes</span>
           
                        <a class="fa fa-thumbs-up" id="likeBtn" role="button" asp-controller="Catalog" asp-action="AddLike" asp-route-animalId="@Model.AnimalId" asp-route-commentId="@comment.Id" asp-route-isLiked="@comment.isLiked"></a>

                    </th>

            </tr>

        }
        </tbody>

    </table>

    <div>
        <tr>
            <th>


        <td>
                    @using (Html.BeginForm("AddComment", "Catalog", new { animalId = Model.AnimalId }, FormMethod.Post))
                    {
          
                      <input name="animalId" type="hidden" value="@Model.AnimalId"/>
                      <input id="commentInput" name="content" type="text" class="input-group-text form-control" maxlength="50"
                       placeholder="Write your comment here" required />
             
                     <input id="commentBtn" class="MyBtn" type="submit" value="Add Comment" />
                     <p id="message"></p>
                 }
        </td>

        </th>
        </tr>


    </div>

    </div>
    </div>


</table>

<script>

    // Length check 

    let likeBtn = document.querySelector("#likeBtn");
    let commentInput = document.querySelector("#commentInput");
    let maxLength = 50;
    let commentBtn = document.querySelector("#commentBtn");
    let message = document.querySelector("#message");
    var checkLength = function(){
        if(commentInput.value.length < maxLength){
            message.innerHTML = (maxLength - commentInput.value.length) + " characters remaining";
        } 
        else{
            message.innerHTML = "No characters remaining";
        }
    }

    setInterval(checkLength, 50);

    // Empty input validation

    function validateForm(){
        if (commentInput.value == null || commentInput.value.trim() === "") {
            showAlert();
            alert("Can't send an empty comment");
            return false;
        }
       
    }
    commentBtn.addEventListener("click", validateForm);





  
</script>



Views/Catalog/Index.cshtml
@model IEnumerable<AnimalPlaceProject.Models.Animal>

@{
    ViewData["Title"] = "Index";
}
<!DOCTYPE html>

<h1>Catalog</h1>


<p class="p">Choose a Category of Pets to Display:</p>

<div class="centeredDiv">
    <form action="/Catalog/Index" method="post" id="CategoryForm">
        <fieldset>
            <select id="categoryName" class="btn btn-secondary btn-md dropdown-toggle" name="categoryName" onchange="SubmitForm()">

                 <option disabled selected>@ViewBag.CurrentCategory </option>
                    <option value="All">All</option>

                @foreach (Category category in ViewBag.Categories)
                {
                    <option value="@category.Name">@category.Name</option>
                }
                 
            </select>

        </fieldset>
    </form>
</div>
<br />

<div>
    <table class="table">
		<tr>
			<th>Portrait</th>
			<th>Name</th>
			<th>find out more and comment</th>
		</tr>
             
             @foreach(var animal in Model)
             {

            <tr>
                <td><img width="200" height="200" src="~/Pictures/@animal.PictureName" /></td>
                <td>@animal.Name</td>
                <td>
                    <a class="btn btn-primary" role="button" asp-controller="Catalog" asp-action="Details" asp-route-animalId="@animal.AnimalId">Details</a>

                </td>

            </tr>

              }
	</table>
</div>



<script>
﻿function SubmitForm() {
	document.getElementById("CategoryForm").submit();
}
</script>

Views/Home/Index.cshtml
@model IEnumerable<AnimalPlaceProject.Models.Animal>
@{
    ViewData["Title"] = "Index";
}

<div class="layOutCenter">



<h1 class="mainText">Animals Place</h1>



@if (ViewBag.User != null)
{
    <p>@ViewBag.User.Username</p>
}

  

    <h3 class="mainText-small">The Place for Animals Information</h3>

   
@{
    var animalsWithMostComments = Model.OrderByDescending(a => a.Comments?.Count).Take(2);
}

</div>

<h5>Popular Animals:</h5>
<table class="table tableMain">
    <tr>
        @foreach (var animal in animalsWithMostComments)
        {
            if (animal.Comments != null && animal.Comments.Any())
            {
                var lastComment = animal.Comments.OrderBy(c => c.Id).Last();

                <th scope="col">
                    <div class="card">
                        <div class="">
                            <img src="~/Pictures/@animal.PictureName" class="animalProfileImg rounded-circle img-responsive shadow-4-strong card img" />
                        </div>
                    <h6>@animal.Name</h6>
                    @if (lastComment != null)
                    {
                        <p class="text-secondary">#Comments: @animal.Comments?.Count</p>
                        <p class="">Last Comment: </p>
                        <p class="text-info">@lastComment.Content</p>

                    }
					</div>
                </th>
            }
        }
       
        

    </tr>
</table>

<h5>Blog:</h5>

<table class="table tableMain">
<th scope="col">
    <div class="card">
        <div class="">
            <img src="~/Pictures/blog.png" class="animalProfileImg rounded-circle img-responsive shadow-4-strong card img" />
        </div>
        <h6>Last Blog Post: </h6>
        <p class="text-secondary">@ViewBag.Post.Title</p>
        <p>@ViewBag.Post.CreateDate.ToString("yyyy-MM-dd")</p>
        <a class="link" asp-area="" asp-controller="Blog" asp-action="Index">More</a>

    </div>
</th>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/styles/bootstrap.css" rel="stylesheet"/>   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/styles/mystyle.css" rel="stylesheet" />
    <script src="~/scripts/jquery.js"></script>
</head>
<body>

    <div>

        <header class="loginSection">
            
            @if (!User.Identity!.IsAuthenticated)
            {
                <div>
                    <a class="" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                </div>
            }
            @if (User.Identity.IsAuthenticated)
            {
                <div>
                    <a class="" asp-area="" asp-controller="Account" asp-action="Logout">Log Out</a>
                </div>
            }

            <nav class="navbar navbar-light" id="Rectangle1" @*style="background-color: #e3f2fd;"*@>
@*
                <img src="https://cdn.discordapp.com/attachments/1059245798317113474/1108650018673537055/Shahar_Shai_A_logo_of_a_pet_Shop_website_4f12318e-a9bb-468d-80cb-6b6d0c956f7a.png" class="navImg" style="width:55px;height:55px;" />

*@
                <a class="nav-link ml-5 myLinks"  asp-area="" asp-controller="Home" asp-action="Index">Home</a>

                <a class="nav-link myLinks" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>

                <a class="nav-link ml-5 myLinks" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>

                @if (User.Identity.IsAuthenticated)
                {
                    <a class="nav-link mr-5 myLinks" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                }

            </nav>
        </header>


    </div>



    @RenderBody()

    <script src="~/scripts/bootstrap.js"></script>
    <script src="~/scripts/popper.js"></script>
    <script src="~/scripts/app.js"></script>


</body>
</html>